// Code generated by ent, DO NOT EDIT.

package document

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the document type in the database.
	Label = "document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDocumentName holds the string denoting the document_name field in the database.
	FieldDocumentName = "document_name"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDocumentType holds the string denoting the document_type field in the database.
	FieldDocumentType = "document_type"
	// FieldGoogleID holds the string denoting the google_id field in the database.
	FieldGoogleID = "google_id"
	// FieldDocumentWebLink holds the string denoting the document_web_link field in the database.
	FieldDocumentWebLink = "document_web_link"
	// FieldDocumentThumnailLink holds the string denoting the document_thumnail_link field in the database.
	FieldDocumentThumnailLink = "document_thumnail_link"
	// FieldDocumentExportLink holds the string denoting the document_export_link field in the database.
	FieldDocumentExportLink = "document_export_link"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the document in the database.
	Table = "document"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "document"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for document fields.
var Columns = []string{
	FieldID,
	FieldDocumentName,
	FieldUserID,
	FieldDocumentType,
	FieldGoogleID,
	FieldDocumentWebLink,
	FieldDocumentThumnailLink,
	FieldDocumentExportLink,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// DocumentType defines the type for the "document_type" enum field.
type DocumentType string

// DocumentTypeOther is the default value of the DocumentType enum.
const DefaultDocumentType = DocumentTypeOther

// DocumentType values.
const (
	DocumentTypeResume      DocumentType = "resume"
	DocumentTypeIDCard      DocumentType = "id_card"
	DocumentTypeCertificate DocumentType = "certificate"
	DocumentTypeOther       DocumentType = "other"
)

func (dt DocumentType) String() string {
	return string(dt)
}

// DocumentTypeValidator is a validator for the "document_type" field enum values. It is called by the builders before save.
func DocumentTypeValidator(dt DocumentType) error {
	switch dt {
	case DocumentTypeResume, DocumentTypeIDCard, DocumentTypeCertificate, DocumentTypeOther:
		return nil
	default:
		return fmt.Errorf("document: invalid enum value for document_type field: %q", dt)
	}
}

// OrderOption defines the ordering options for the Document queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDocumentName orders the results by the document_name field.
func ByDocumentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentName, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDocumentType orders the results by the document_type field.
func ByDocumentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentType, opts...).ToFunc()
}

// ByGoogleID orders the results by the google_id field.
func ByGoogleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoogleID, opts...).ToFunc()
}

// ByDocumentWebLink orders the results by the document_web_link field.
func ByDocumentWebLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentWebLink, opts...).ToFunc()
}

// ByDocumentThumnailLink orders the results by the document_thumnail_link field.
func ByDocumentThumnailLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentThumnailLink, opts...).ToFunc()
}

// ByDocumentExportLink orders the results by the document_export_link field.
func ByDocumentExportLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentExportLink, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
