// Code generated by ent, DO NOT EDIT.

package document

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldID, id))
}

// DocumentName applies equality check predicate on the "document_name" field. It's identical to DocumentNameEQ.
func DocumentName(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentName, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUserID, v))
}

// GoogleID applies equality check predicate on the "google_id" field. It's identical to GoogleIDEQ.
func GoogleID(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldGoogleID, v))
}

// DocumentWebLink applies equality check predicate on the "document_web_link" field. It's identical to DocumentWebLinkEQ.
func DocumentWebLink(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentWebLink, v))
}

// DocumentThumnailLink applies equality check predicate on the "document_thumnail_link" field. It's identical to DocumentThumnailLinkEQ.
func DocumentThumnailLink(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentThumnailLink, v))
}

// DocumentExportLink applies equality check predicate on the "document_export_link" field. It's identical to DocumentExportLinkEQ.
func DocumentExportLink(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentExportLink, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUpdatedAt, v))
}

// DocumentNameEQ applies the EQ predicate on the "document_name" field.
func DocumentNameEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentName, v))
}

// DocumentNameNEQ applies the NEQ predicate on the "document_name" field.
func DocumentNameNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocumentName, v))
}

// DocumentNameIn applies the In predicate on the "document_name" field.
func DocumentNameIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocumentName, vs...))
}

// DocumentNameNotIn applies the NotIn predicate on the "document_name" field.
func DocumentNameNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocumentName, vs...))
}

// DocumentNameGT applies the GT predicate on the "document_name" field.
func DocumentNameGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDocumentName, v))
}

// DocumentNameGTE applies the GTE predicate on the "document_name" field.
func DocumentNameGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDocumentName, v))
}

// DocumentNameLT applies the LT predicate on the "document_name" field.
func DocumentNameLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDocumentName, v))
}

// DocumentNameLTE applies the LTE predicate on the "document_name" field.
func DocumentNameLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDocumentName, v))
}

// DocumentNameContains applies the Contains predicate on the "document_name" field.
func DocumentNameContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDocumentName, v))
}

// DocumentNameHasPrefix applies the HasPrefix predicate on the "document_name" field.
func DocumentNameHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDocumentName, v))
}

// DocumentNameHasSuffix applies the HasSuffix predicate on the "document_name" field.
func DocumentNameHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDocumentName, v))
}

// DocumentNameEqualFold applies the EqualFold predicate on the "document_name" field.
func DocumentNameEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDocumentName, v))
}

// DocumentNameContainsFold applies the ContainsFold predicate on the "document_name" field.
func DocumentNameContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDocumentName, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldUserID, vs...))
}

// DocumentTypeEQ applies the EQ predicate on the "document_type" field.
func DocumentTypeEQ(v DocumentType) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentType, v))
}

// DocumentTypeNEQ applies the NEQ predicate on the "document_type" field.
func DocumentTypeNEQ(v DocumentType) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocumentType, v))
}

// DocumentTypeIn applies the In predicate on the "document_type" field.
func DocumentTypeIn(vs ...DocumentType) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocumentType, vs...))
}

// DocumentTypeNotIn applies the NotIn predicate on the "document_type" field.
func DocumentTypeNotIn(vs ...DocumentType) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocumentType, vs...))
}

// GoogleIDEQ applies the EQ predicate on the "google_id" field.
func GoogleIDEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldGoogleID, v))
}

// GoogleIDNEQ applies the NEQ predicate on the "google_id" field.
func GoogleIDNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldGoogleID, v))
}

// GoogleIDIn applies the In predicate on the "google_id" field.
func GoogleIDIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldGoogleID, vs...))
}

// GoogleIDNotIn applies the NotIn predicate on the "google_id" field.
func GoogleIDNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldGoogleID, vs...))
}

// GoogleIDGT applies the GT predicate on the "google_id" field.
func GoogleIDGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldGoogleID, v))
}

// GoogleIDGTE applies the GTE predicate on the "google_id" field.
func GoogleIDGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldGoogleID, v))
}

// GoogleIDLT applies the LT predicate on the "google_id" field.
func GoogleIDLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldGoogleID, v))
}

// GoogleIDLTE applies the LTE predicate on the "google_id" field.
func GoogleIDLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldGoogleID, v))
}

// GoogleIDContains applies the Contains predicate on the "google_id" field.
func GoogleIDContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldGoogleID, v))
}

// GoogleIDHasPrefix applies the HasPrefix predicate on the "google_id" field.
func GoogleIDHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldGoogleID, v))
}

// GoogleIDHasSuffix applies the HasSuffix predicate on the "google_id" field.
func GoogleIDHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldGoogleID, v))
}

// GoogleIDEqualFold applies the EqualFold predicate on the "google_id" field.
func GoogleIDEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldGoogleID, v))
}

// GoogleIDContainsFold applies the ContainsFold predicate on the "google_id" field.
func GoogleIDContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldGoogleID, v))
}

// DocumentWebLinkEQ applies the EQ predicate on the "document_web_link" field.
func DocumentWebLinkEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentWebLink, v))
}

// DocumentWebLinkNEQ applies the NEQ predicate on the "document_web_link" field.
func DocumentWebLinkNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocumentWebLink, v))
}

// DocumentWebLinkIn applies the In predicate on the "document_web_link" field.
func DocumentWebLinkIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocumentWebLink, vs...))
}

// DocumentWebLinkNotIn applies the NotIn predicate on the "document_web_link" field.
func DocumentWebLinkNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocumentWebLink, vs...))
}

// DocumentWebLinkGT applies the GT predicate on the "document_web_link" field.
func DocumentWebLinkGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDocumentWebLink, v))
}

// DocumentWebLinkGTE applies the GTE predicate on the "document_web_link" field.
func DocumentWebLinkGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDocumentWebLink, v))
}

// DocumentWebLinkLT applies the LT predicate on the "document_web_link" field.
func DocumentWebLinkLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDocumentWebLink, v))
}

// DocumentWebLinkLTE applies the LTE predicate on the "document_web_link" field.
func DocumentWebLinkLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDocumentWebLink, v))
}

// DocumentWebLinkContains applies the Contains predicate on the "document_web_link" field.
func DocumentWebLinkContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDocumentWebLink, v))
}

// DocumentWebLinkHasPrefix applies the HasPrefix predicate on the "document_web_link" field.
func DocumentWebLinkHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDocumentWebLink, v))
}

// DocumentWebLinkHasSuffix applies the HasSuffix predicate on the "document_web_link" field.
func DocumentWebLinkHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDocumentWebLink, v))
}

// DocumentWebLinkIsNil applies the IsNil predicate on the "document_web_link" field.
func DocumentWebLinkIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldDocumentWebLink))
}

// DocumentWebLinkNotNil applies the NotNil predicate on the "document_web_link" field.
func DocumentWebLinkNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldDocumentWebLink))
}

// DocumentWebLinkEqualFold applies the EqualFold predicate on the "document_web_link" field.
func DocumentWebLinkEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDocumentWebLink, v))
}

// DocumentWebLinkContainsFold applies the ContainsFold predicate on the "document_web_link" field.
func DocumentWebLinkContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDocumentWebLink, v))
}

// DocumentThumnailLinkEQ applies the EQ predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkNEQ applies the NEQ predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkIn applies the In predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocumentThumnailLink, vs...))
}

// DocumentThumnailLinkNotIn applies the NotIn predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocumentThumnailLink, vs...))
}

// DocumentThumnailLinkGT applies the GT predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkGTE applies the GTE predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkLT applies the LT predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkLTE applies the LTE predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkContains applies the Contains predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkHasPrefix applies the HasPrefix predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkHasSuffix applies the HasSuffix predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkIsNil applies the IsNil predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldDocumentThumnailLink))
}

// DocumentThumnailLinkNotNil applies the NotNil predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldDocumentThumnailLink))
}

// DocumentThumnailLinkEqualFold applies the EqualFold predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDocumentThumnailLink, v))
}

// DocumentThumnailLinkContainsFold applies the ContainsFold predicate on the "document_thumnail_link" field.
func DocumentThumnailLinkContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDocumentThumnailLink, v))
}

// DocumentExportLinkEQ applies the EQ predicate on the "document_export_link" field.
func DocumentExportLinkEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocumentExportLink, v))
}

// DocumentExportLinkNEQ applies the NEQ predicate on the "document_export_link" field.
func DocumentExportLinkNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocumentExportLink, v))
}

// DocumentExportLinkIn applies the In predicate on the "document_export_link" field.
func DocumentExportLinkIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocumentExportLink, vs...))
}

// DocumentExportLinkNotIn applies the NotIn predicate on the "document_export_link" field.
func DocumentExportLinkNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocumentExportLink, vs...))
}

// DocumentExportLinkGT applies the GT predicate on the "document_export_link" field.
func DocumentExportLinkGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDocumentExportLink, v))
}

// DocumentExportLinkGTE applies the GTE predicate on the "document_export_link" field.
func DocumentExportLinkGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDocumentExportLink, v))
}

// DocumentExportLinkLT applies the LT predicate on the "document_export_link" field.
func DocumentExportLinkLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDocumentExportLink, v))
}

// DocumentExportLinkLTE applies the LTE predicate on the "document_export_link" field.
func DocumentExportLinkLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDocumentExportLink, v))
}

// DocumentExportLinkContains applies the Contains predicate on the "document_export_link" field.
func DocumentExportLinkContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDocumentExportLink, v))
}

// DocumentExportLinkHasPrefix applies the HasPrefix predicate on the "document_export_link" field.
func DocumentExportLinkHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDocumentExportLink, v))
}

// DocumentExportLinkHasSuffix applies the HasSuffix predicate on the "document_export_link" field.
func DocumentExportLinkHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDocumentExportLink, v))
}

// DocumentExportLinkIsNil applies the IsNil predicate on the "document_export_link" field.
func DocumentExportLinkIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldDocumentExportLink))
}

// DocumentExportLinkNotNil applies the NotNil predicate on the "document_export_link" field.
func DocumentExportLinkNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldDocumentExportLink))
}

// DocumentExportLinkEqualFold applies the EqualFold predicate on the "document_export_link" field.
func DocumentExportLinkEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDocumentExportLink, v))
}

// DocumentExportLinkContainsFold applies the ContainsFold predicate on the "document_export_link" field.
func DocumentExportLinkContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDocumentExportLink, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Document) predicate.Document {
	return predicate.Document(sql.NotPredicates(p))
}
