// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EducationColumns holds the columns for the "education" table.
	EducationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "institute_name", Type: field.TypeString},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "mode_of_study", Type: field.TypeString},
		{Name: "degree_type", Type: field.TypeString},
		{Name: "area_of_study", Type: field.TypeString},
		{Name: "currently_studying", Type: field.TypeBool, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUint, SchemaType: map[string]string{"postgres": "serial"}},
	}
	// EducationTable holds the schema information for the "education" table.
	EducationTable = &schema.Table{
		Name:       "education",
		Columns:    EducationColumns,
		PrimaryKey: []*schema.Column{EducationColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "education_users_educations",
				Columns:    []*schema.Column{EducationColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ExperienceColumns holds the columns for the "experience" table.
	ExperienceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "company_name", Type: field.TypeString},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "current_place", Type: field.TypeBool, Nullable: true},
		{Name: "position", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeUint, SchemaType: map[string]string{"postgres": "serial"}},
	}
	// ExperienceTable holds the schema information for the "experience" table.
	ExperienceTable = &schema.Table{
		Name:       "experience",
		Columns:    ExperienceColumns,
		PrimaryKey: []*schema.Column{ExperienceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "experience_users_experiences",
				Columns:    []*schema.Column{ExperienceColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SkillColumns holds the columns for the "skill" table.
	SkillColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// SkillTable holds the schema information for the "skill" table.
	SkillTable = &schema.Table{
		Name:       "skill",
		Columns:    SkillColumns,
		PrimaryKey: []*schema.Column{SkillColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "first_name", Type: field.TypeString, Nullable: true},
		{Name: "last_name", Type: field.TypeString, Nullable: true},
		{Name: "dob", Type: field.TypeTime, Nullable: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "github_username", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "mobile_number", Type: field.TypeInt32, Nullable: true},
		{Name: "address_block", Type: field.TypeString, Nullable: true},
		{Name: "address_street", Type: field.TypeString, Nullable: true},
		{Name: "recidential_country", Type: field.TypeString, Nullable: true},
		{Name: "nationality", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserSkillAssociationColumns holds the columns for the "user_skill_association" table.
	UserSkillAssociationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "percentage", Type: field.TypeInt32, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "experience_id", Type: field.TypeUint, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "skill_id", Type: field.TypeUint, SchemaType: map[string]string{"postgres": "serial"}},
	}
	// UserSkillAssociationTable holds the schema information for the "user_skill_association" table.
	UserSkillAssociationTable = &schema.Table{
		Name:       "user_skill_association",
		Columns:    UserSkillAssociationColumns,
		PrimaryKey: []*schema.Column{UserSkillAssociationColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_skill_association_experience_user_skill_association",
				Columns:    []*schema.Column{UserSkillAssociationColumns[4]},
				RefColumns: []*schema.Column{ExperienceColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_skill_association_skill_user_skill_association",
				Columns:    []*schema.Column{UserSkillAssociationColumns[5]},
				RefColumns: []*schema.Column{SkillColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userskillassociation_experience_id_skill_id",
				Unique:  true,
				Columns: []*schema.Column{UserSkillAssociationColumns[4], UserSkillAssociationColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EducationTable,
		ExperienceTable,
		SkillTable,
		UsersTable,
		UserSkillAssociationTable,
	}
)

func init() {
	EducationTable.ForeignKeys[0].RefTable = UsersTable
	EducationTable.Annotation = &entsql.Annotation{
		Table: "education",
	}
	ExperienceTable.ForeignKeys[0].RefTable = UsersTable
	ExperienceTable.Annotation = &entsql.Annotation{
		Table: "experience",
	}
	SkillTable.Annotation = &entsql.Annotation{
		Table: "skill",
	}
	UserSkillAssociationTable.ForeignKeys[0].RefTable = ExperienceTable
	UserSkillAssociationTable.ForeignKeys[1].RefTable = SkillTable
	UserSkillAssociationTable.Annotation = &entsql.Annotation{
		Table: "user_skill_association",
	}
}
