// Code generated by ent, DO NOT EDIT.

package skill

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCategory, v))
}

// YearsOfExperience applies equality check predicate on the "years_of_experience" field. It's identical to YearsOfExperienceEQ.
func YearsOfExperience(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldYearsOfExperience, v))
}

// ProficiencyLevel applies equality check predicate on the "proficiency_level" field. It's identical to ProficiencyLevelEQ.
func ProficiencyLevel(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldProficiencyLevel, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldIcon, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldCategory, v))
}

// YearsOfExperienceEQ applies the EQ predicate on the "years_of_experience" field.
func YearsOfExperienceEQ(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldYearsOfExperience, v))
}

// YearsOfExperienceNEQ applies the NEQ predicate on the "years_of_experience" field.
func YearsOfExperienceNEQ(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldYearsOfExperience, v))
}

// YearsOfExperienceIn applies the In predicate on the "years_of_experience" field.
func YearsOfExperienceIn(vs ...uint) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldYearsOfExperience, vs...))
}

// YearsOfExperienceNotIn applies the NotIn predicate on the "years_of_experience" field.
func YearsOfExperienceNotIn(vs ...uint) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldYearsOfExperience, vs...))
}

// YearsOfExperienceGT applies the GT predicate on the "years_of_experience" field.
func YearsOfExperienceGT(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldYearsOfExperience, v))
}

// YearsOfExperienceGTE applies the GTE predicate on the "years_of_experience" field.
func YearsOfExperienceGTE(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldYearsOfExperience, v))
}

// YearsOfExperienceLT applies the LT predicate on the "years_of_experience" field.
func YearsOfExperienceLT(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldYearsOfExperience, v))
}

// YearsOfExperienceLTE applies the LTE predicate on the "years_of_experience" field.
func YearsOfExperienceLTE(v uint) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldYearsOfExperience, v))
}

// YearsOfExperienceIsNil applies the IsNil predicate on the "years_of_experience" field.
func YearsOfExperienceIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldYearsOfExperience))
}

// YearsOfExperienceNotNil applies the NotNil predicate on the "years_of_experience" field.
func YearsOfExperienceNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldYearsOfExperience))
}

// ProficiencyLevelEQ applies the EQ predicate on the "proficiency_level" field.
func ProficiencyLevelEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldProficiencyLevel, v))
}

// ProficiencyLevelNEQ applies the NEQ predicate on the "proficiency_level" field.
func ProficiencyLevelNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldProficiencyLevel, v))
}

// ProficiencyLevelIn applies the In predicate on the "proficiency_level" field.
func ProficiencyLevelIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldProficiencyLevel, vs...))
}

// ProficiencyLevelNotIn applies the NotIn predicate on the "proficiency_level" field.
func ProficiencyLevelNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldProficiencyLevel, vs...))
}

// ProficiencyLevelGT applies the GT predicate on the "proficiency_level" field.
func ProficiencyLevelGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldProficiencyLevel, v))
}

// ProficiencyLevelGTE applies the GTE predicate on the "proficiency_level" field.
func ProficiencyLevelGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldProficiencyLevel, v))
}

// ProficiencyLevelLT applies the LT predicate on the "proficiency_level" field.
func ProficiencyLevelLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldProficiencyLevel, v))
}

// ProficiencyLevelLTE applies the LTE predicate on the "proficiency_level" field.
func ProficiencyLevelLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldProficiencyLevel, v))
}

// ProficiencyLevelContains applies the Contains predicate on the "proficiency_level" field.
func ProficiencyLevelContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldProficiencyLevel, v))
}

// ProficiencyLevelHasPrefix applies the HasPrefix predicate on the "proficiency_level" field.
func ProficiencyLevelHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldProficiencyLevel, v))
}

// ProficiencyLevelHasSuffix applies the HasSuffix predicate on the "proficiency_level" field.
func ProficiencyLevelHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldProficiencyLevel, v))
}

// ProficiencyLevelIsNil applies the IsNil predicate on the "proficiency_level" field.
func ProficiencyLevelIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldProficiencyLevel))
}

// ProficiencyLevelNotNil applies the NotNil predicate on the "proficiency_level" field.
func ProficiencyLevelNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldProficiencyLevel))
}

// ProficiencyLevelEqualFold applies the EqualFold predicate on the "proficiency_level" field.
func ProficiencyLevelEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldProficiencyLevel, v))
}

// ProficiencyLevelContainsFold applies the ContainsFold predicate on the "proficiency_level" field.
func ProficiencyLevelContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldProficiencyLevel, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldIcon, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldIcon))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldIcon, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldUpdatedAt))
}

// HasUserSkillAssociation applies the HasEdge predicate on the "user_skill_association" edge.
func HasUserSkillAssociation() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserSkillAssociationTable, UserSkillAssociationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserSkillAssociationWith applies the HasEdge predicate on the "user_skill_association" edge with a given conditions (other predicates).
func HasUserSkillAssociationWith(preds ...predicate.UserSkillAssociation) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newUserSkillAssociationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTechstack applies the HasEdge predicate on the "techstack" edge.
func HasTechstack() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TechstackTable, TechstackColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTechstackWith applies the HasEdge predicate on the "techstack" edge with a given conditions (other predicates).
func HasTechstackWith(preds ...predicate.TechSctack) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newTechstackStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ProjectTable, ProjectPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.NotPredicates(p))
}
