// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/document"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentCreate is the builder for creating a Document entity.
type DocumentCreate struct {
	config
	mutation *DocumentMutation
	hooks    []Hook
}

// SetDocumentName sets the "document_name" field.
func (_c *DocumentCreate) SetDocumentName(v string) *DocumentCreate {
	_c.mutation.SetDocumentName(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DocumentCreate) SetUserID(v uint) *DocumentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDocumentType sets the "document_type" field.
func (_c *DocumentCreate) SetDocumentType(v document.DocumentType) *DocumentCreate {
	_c.mutation.SetDocumentType(v)
	return _c
}

// SetNillableDocumentType sets the "document_type" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDocumentType(v *document.DocumentType) *DocumentCreate {
	if v != nil {
		_c.SetDocumentType(*v)
	}
	return _c
}

// SetGoogleID sets the "google_id" field.
func (_c *DocumentCreate) SetGoogleID(v string) *DocumentCreate {
	_c.mutation.SetGoogleID(v)
	return _c
}

// SetDocumentWebLink sets the "document_web_link" field.
func (_c *DocumentCreate) SetDocumentWebLink(v string) *DocumentCreate {
	_c.mutation.SetDocumentWebLink(v)
	return _c
}

// SetNillableDocumentWebLink sets the "document_web_link" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDocumentWebLink(v *string) *DocumentCreate {
	if v != nil {
		_c.SetDocumentWebLink(*v)
	}
	return _c
}

// SetDocumentThumnailLink sets the "document_thumnail_link" field.
func (_c *DocumentCreate) SetDocumentThumnailLink(v string) *DocumentCreate {
	_c.mutation.SetDocumentThumnailLink(v)
	return _c
}

// SetNillableDocumentThumnailLink sets the "document_thumnail_link" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDocumentThumnailLink(v *string) *DocumentCreate {
	if v != nil {
		_c.SetDocumentThumnailLink(*v)
	}
	return _c
}

// SetDocumentExportLink sets the "document_export_link" field.
func (_c *DocumentCreate) SetDocumentExportLink(v string) *DocumentCreate {
	_c.mutation.SetDocumentExportLink(v)
	return _c
}

// SetNillableDocumentExportLink sets the "document_export_link" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDocumentExportLink(v *string) *DocumentCreate {
	if v != nil {
		_c.SetDocumentExportLink(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentCreate) SetCreatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DocumentCreate) SetUpdatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableUpdatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentCreate) SetID(v uint) *DocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DocumentCreate) SetUser(v *User) *DocumentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DocumentMutation object of the builder.
func (_c *DocumentCreate) Mutation() *DocumentMutation {
	return _c.mutation
}

// Save creates the Document in the database.
func (_c *DocumentCreate) Save(ctx context.Context) (*Document, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentCreate) SaveX(ctx context.Context) *Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentCreate) defaults() {
	if _, ok := _c.mutation.DocumentType(); !ok {
		v := document.DefaultDocumentType
		_c.mutation.SetDocumentType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := document.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := document.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentCreate) check() error {
	if _, ok := _c.mutation.DocumentName(); !ok {
		return &ValidationError{Name: "document_name", err: errors.New(`ent: missing required field "Document.document_name"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Document.user_id"`)}
	}
	if _, ok := _c.mutation.DocumentType(); !ok {
		return &ValidationError{Name: "document_type", err: errors.New(`ent: missing required field "Document.document_type"`)}
	}
	if v, ok := _c.mutation.DocumentType(); ok {
		if err := document.DocumentTypeValidator(v); err != nil {
			return &ValidationError{Name: "document_type", err: fmt.Errorf(`ent: validator failed for field "Document.document_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GoogleID(); !ok {
		return &ValidationError{Name: "google_id", err: errors.New(`ent: missing required field "Document.google_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Document.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Document.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Document.user"`)}
	}
	return nil
}

func (_c *DocumentCreate) sqlSave(ctx context.Context) (*Document, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentCreate) createSpec() (*Document, *sqlgraph.CreateSpec) {
	var (
		_node = &Document{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(document.Table, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DocumentName(); ok {
		_spec.SetField(document.FieldDocumentName, field.TypeString, value)
		_node.DocumentName = value
	}
	if value, ok := _c.mutation.DocumentType(); ok {
		_spec.SetField(document.FieldDocumentType, field.TypeEnum, value)
		_node.DocumentType = value
	}
	if value, ok := _c.mutation.GoogleID(); ok {
		_spec.SetField(document.FieldGoogleID, field.TypeString, value)
		_node.GoogleID = value
	}
	if value, ok := _c.mutation.DocumentWebLink(); ok {
		_spec.SetField(document.FieldDocumentWebLink, field.TypeString, value)
		_node.DocumentWebLink = value
	}
	if value, ok := _c.mutation.DocumentThumnailLink(); ok {
		_spec.SetField(document.FieldDocumentThumnailLink, field.TypeString, value)
		_node.DocumentThumnailLink = value
	}
	if value, ok := _c.mutation.DocumentExportLink(); ok {
		_spec.SetField(document.FieldDocumentExportLink, field.TypeString, value)
		_node.DocumentExportLink = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.UserTable,
			Columns: []string{document.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentCreateBulk is the builder for creating many Document entities in bulk.
type DocumentCreateBulk struct {
	config
	err      error
	builders []*DocumentCreate
}

// Save creates the Document entities in the database.
func (_c *DocumentCreateBulk) Save(ctx context.Context) ([]*Document, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Document, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentCreateBulk) SaveX(ctx context.Context) []*Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
