// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/education"
	"api/ent/predicate"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EducationUpdate is the builder for updating Education entities.
type EducationUpdate struct {
	config
	hooks    []Hook
	mutation *EducationMutation
}

// Where appends a list predicates to the EducationUpdate builder.
func (_u *EducationUpdate) Where(ps ...predicate.Education) *EducationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstituteName sets the "institute_name" field.
func (_u *EducationUpdate) SetInstituteName(v string) *EducationUpdate {
	_u.mutation.SetInstituteName(v)
	return _u
}

// SetNillableInstituteName sets the "institute_name" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableInstituteName(v *string) *EducationUpdate {
	if v != nil {
		_u.SetInstituteName(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EducationUpdate) SetStartDate(v time.Time) *EducationUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableStartDate(v *time.Time) *EducationUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EducationUpdate) SetEndDate(v time.Time) *EducationUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableEndDate(v *time.Time) *EducationUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EducationUpdate) ClearEndDate() *EducationUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EducationUpdate) SetUserID(v uint) *EducationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableUserID(v *uint) *EducationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetModeOfStudy sets the "mode_of_study" field.
func (_u *EducationUpdate) SetModeOfStudy(v string) *EducationUpdate {
	_u.mutation.SetModeOfStudy(v)
	return _u
}

// SetNillableModeOfStudy sets the "mode_of_study" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableModeOfStudy(v *string) *EducationUpdate {
	if v != nil {
		_u.SetModeOfStudy(*v)
	}
	return _u
}

// SetDegreeType sets the "degree_type" field.
func (_u *EducationUpdate) SetDegreeType(v string) *EducationUpdate {
	_u.mutation.SetDegreeType(v)
	return _u
}

// SetNillableDegreeType sets the "degree_type" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableDegreeType(v *string) *EducationUpdate {
	if v != nil {
		_u.SetDegreeType(*v)
	}
	return _u
}

// SetAreaOfStudy sets the "area_of_study" field.
func (_u *EducationUpdate) SetAreaOfStudy(v string) *EducationUpdate {
	_u.mutation.SetAreaOfStudy(v)
	return _u
}

// SetNillableAreaOfStudy sets the "area_of_study" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableAreaOfStudy(v *string) *EducationUpdate {
	if v != nil {
		_u.SetAreaOfStudy(*v)
	}
	return _u
}

// SetCurrentlyStudying sets the "currently_studying" field.
func (_u *EducationUpdate) SetCurrentlyStudying(v bool) *EducationUpdate {
	_u.mutation.SetCurrentlyStudying(v)
	return _u
}

// SetNillableCurrentlyStudying sets the "currently_studying" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableCurrentlyStudying(v *bool) *EducationUpdate {
	if v != nil {
		_u.SetCurrentlyStudying(*v)
	}
	return _u
}

// ClearCurrentlyStudying clears the value of the "currently_studying" field.
func (_u *EducationUpdate) ClearCurrentlyStudying() *EducationUpdate {
	_u.mutation.ClearCurrentlyStudying()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EducationUpdate) SetDescription(v string) *EducationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableDescription(v *string) *EducationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EducationUpdate) ClearDescription() *EducationUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EducationUpdate) SetCreatedAt(v time.Time) *EducationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EducationUpdate) SetNillableCreatedAt(v *time.Time) *EducationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EducationUpdate) SetUpdatedAt(v time.Time) *EducationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EducationUpdate) SetUser(v *User) *EducationUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EducationMutation object of the builder.
func (_u *EducationUpdate) Mutation() *EducationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EducationUpdate) ClearUser() *EducationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EducationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EducationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EducationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EducationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EducationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := education.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EducationUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Education.user"`)
	}
	return nil
}

func (_u *EducationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(education.Table, education.Columns, sqlgraph.NewFieldSpec(education.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstituteName(); ok {
		_spec.SetField(education.FieldInstituteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(education.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ModeOfStudy(); ok {
		_spec.SetField(education.FieldModeOfStudy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DegreeType(); ok {
		_spec.SetField(education.FieldDegreeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AreaOfStudy(); ok {
		_spec.SetField(education.FieldAreaOfStudy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentlyStudying(); ok {
		_spec.SetField(education.FieldCurrentlyStudying, field.TypeBool, value)
	}
	if _u.mutation.CurrentlyStudyingCleared() {
		_spec.ClearField(education.FieldCurrentlyStudying, field.TypeBool)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(education.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(education.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(education.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{education.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EducationUpdateOne is the builder for updating a single Education entity.
type EducationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EducationMutation
}

// SetInstituteName sets the "institute_name" field.
func (_u *EducationUpdateOne) SetInstituteName(v string) *EducationUpdateOne {
	_u.mutation.SetInstituteName(v)
	return _u
}

// SetNillableInstituteName sets the "institute_name" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableInstituteName(v *string) *EducationUpdateOne {
	if v != nil {
		_u.SetInstituteName(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EducationUpdateOne) SetStartDate(v time.Time) *EducationUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableStartDate(v *time.Time) *EducationUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EducationUpdateOne) SetEndDate(v time.Time) *EducationUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableEndDate(v *time.Time) *EducationUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EducationUpdateOne) ClearEndDate() *EducationUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EducationUpdateOne) SetUserID(v uint) *EducationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableUserID(v *uint) *EducationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetModeOfStudy sets the "mode_of_study" field.
func (_u *EducationUpdateOne) SetModeOfStudy(v string) *EducationUpdateOne {
	_u.mutation.SetModeOfStudy(v)
	return _u
}

// SetNillableModeOfStudy sets the "mode_of_study" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableModeOfStudy(v *string) *EducationUpdateOne {
	if v != nil {
		_u.SetModeOfStudy(*v)
	}
	return _u
}

// SetDegreeType sets the "degree_type" field.
func (_u *EducationUpdateOne) SetDegreeType(v string) *EducationUpdateOne {
	_u.mutation.SetDegreeType(v)
	return _u
}

// SetNillableDegreeType sets the "degree_type" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableDegreeType(v *string) *EducationUpdateOne {
	if v != nil {
		_u.SetDegreeType(*v)
	}
	return _u
}

// SetAreaOfStudy sets the "area_of_study" field.
func (_u *EducationUpdateOne) SetAreaOfStudy(v string) *EducationUpdateOne {
	_u.mutation.SetAreaOfStudy(v)
	return _u
}

// SetNillableAreaOfStudy sets the "area_of_study" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableAreaOfStudy(v *string) *EducationUpdateOne {
	if v != nil {
		_u.SetAreaOfStudy(*v)
	}
	return _u
}

// SetCurrentlyStudying sets the "currently_studying" field.
func (_u *EducationUpdateOne) SetCurrentlyStudying(v bool) *EducationUpdateOne {
	_u.mutation.SetCurrentlyStudying(v)
	return _u
}

// SetNillableCurrentlyStudying sets the "currently_studying" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableCurrentlyStudying(v *bool) *EducationUpdateOne {
	if v != nil {
		_u.SetCurrentlyStudying(*v)
	}
	return _u
}

// ClearCurrentlyStudying clears the value of the "currently_studying" field.
func (_u *EducationUpdateOne) ClearCurrentlyStudying() *EducationUpdateOne {
	_u.mutation.ClearCurrentlyStudying()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EducationUpdateOne) SetDescription(v string) *EducationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableDescription(v *string) *EducationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EducationUpdateOne) ClearDescription() *EducationUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EducationUpdateOne) SetCreatedAt(v time.Time) *EducationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EducationUpdateOne) SetNillableCreatedAt(v *time.Time) *EducationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EducationUpdateOne) SetUpdatedAt(v time.Time) *EducationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EducationUpdateOne) SetUser(v *User) *EducationUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EducationMutation object of the builder.
func (_u *EducationUpdateOne) Mutation() *EducationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EducationUpdateOne) ClearUser() *EducationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the EducationUpdate builder.
func (_u *EducationUpdateOne) Where(ps ...predicate.Education) *EducationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EducationUpdateOne) Select(field string, fields ...string) *EducationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Education entity.
func (_u *EducationUpdateOne) Save(ctx context.Context) (*Education, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EducationUpdateOne) SaveX(ctx context.Context) *Education {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EducationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EducationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EducationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := education.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EducationUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Education.user"`)
	}
	return nil
}

func (_u *EducationUpdateOne) sqlSave(ctx context.Context) (_node *Education, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(education.Table, education.Columns, sqlgraph.NewFieldSpec(education.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Education.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, education.FieldID)
		for _, f := range fields {
			if !education.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != education.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstituteName(); ok {
		_spec.SetField(education.FieldInstituteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(education.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ModeOfStudy(); ok {
		_spec.SetField(education.FieldModeOfStudy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DegreeType(); ok {
		_spec.SetField(education.FieldDegreeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AreaOfStudy(); ok {
		_spec.SetField(education.FieldAreaOfStudy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentlyStudying(); ok {
		_spec.SetField(education.FieldCurrentlyStudying, field.TypeBool, value)
	}
	if _u.mutation.CurrentlyStudyingCleared() {
		_spec.ClearField(education.FieldCurrentlyStudying, field.TypeBool)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(education.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(education.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(education.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Education{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{education.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
