// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/education"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EducationCreate is the builder for creating a Education entity.
type EducationCreate struct {
	config
	mutation *EducationMutation
	hooks    []Hook
}

// SetInstituteName sets the "institute_name" field.
func (_c *EducationCreate) SetInstituteName(v string) *EducationCreate {
	_c.mutation.SetInstituteName(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *EducationCreate) SetStartDate(v time.Time) *EducationCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *EducationCreate) SetEndDate(v time.Time) *EducationCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *EducationCreate) SetNillableEndDate(v *time.Time) *EducationCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EducationCreate) SetUserID(v uint) *EducationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetModeOfStudy sets the "mode_of_study" field.
func (_c *EducationCreate) SetModeOfStudy(v string) *EducationCreate {
	_c.mutation.SetModeOfStudy(v)
	return _c
}

// SetDegreeType sets the "degree_type" field.
func (_c *EducationCreate) SetDegreeType(v string) *EducationCreate {
	_c.mutation.SetDegreeType(v)
	return _c
}

// SetAreaOfStudy sets the "area_of_study" field.
func (_c *EducationCreate) SetAreaOfStudy(v string) *EducationCreate {
	_c.mutation.SetAreaOfStudy(v)
	return _c
}

// SetCurrentlyStudying sets the "currently_studying" field.
func (_c *EducationCreate) SetCurrentlyStudying(v bool) *EducationCreate {
	_c.mutation.SetCurrentlyStudying(v)
	return _c
}

// SetNillableCurrentlyStudying sets the "currently_studying" field if the given value is not nil.
func (_c *EducationCreate) SetNillableCurrentlyStudying(v *bool) *EducationCreate {
	if v != nil {
		_c.SetCurrentlyStudying(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *EducationCreate) SetDescription(v string) *EducationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EducationCreate) SetNillableDescription(v *string) *EducationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EducationCreate) SetCreatedAt(v time.Time) *EducationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EducationCreate) SetNillableCreatedAt(v *time.Time) *EducationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EducationCreate) SetUpdatedAt(v time.Time) *EducationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EducationCreate) SetNillableUpdatedAt(v *time.Time) *EducationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EducationCreate) SetID(v uint) *EducationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EducationCreate) SetUser(v *User) *EducationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EducationMutation object of the builder.
func (_c *EducationCreate) Mutation() *EducationMutation {
	return _c.mutation
}

// Save creates the Education in the database.
func (_c *EducationCreate) Save(ctx context.Context) (*Education, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EducationCreate) SaveX(ctx context.Context) *Education {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EducationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EducationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EducationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := education.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := education.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EducationCreate) check() error {
	if _, ok := _c.mutation.InstituteName(); !ok {
		return &ValidationError{Name: "institute_name", err: errors.New(`ent: missing required field "Education.institute_name"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Education.start_date"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Education.user_id"`)}
	}
	if _, ok := _c.mutation.ModeOfStudy(); !ok {
		return &ValidationError{Name: "mode_of_study", err: errors.New(`ent: missing required field "Education.mode_of_study"`)}
	}
	if _, ok := _c.mutation.DegreeType(); !ok {
		return &ValidationError{Name: "degree_type", err: errors.New(`ent: missing required field "Education.degree_type"`)}
	}
	if _, ok := _c.mutation.AreaOfStudy(); !ok {
		return &ValidationError{Name: "area_of_study", err: errors.New(`ent: missing required field "Education.area_of_study"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Education.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Education.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Education.user"`)}
	}
	return nil
}

func (_c *EducationCreate) sqlSave(ctx context.Context) (*Education, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EducationCreate) createSpec() (*Education, *sqlgraph.CreateSpec) {
	var (
		_node = &Education{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(education.Table, sqlgraph.NewFieldSpec(education.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.InstituteName(); ok {
		_spec.SetField(education.FieldInstituteName, field.TypeString, value)
		_node.InstituteName = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.ModeOfStudy(); ok {
		_spec.SetField(education.FieldModeOfStudy, field.TypeString, value)
		_node.ModeOfStudy = value
	}
	if value, ok := _c.mutation.DegreeType(); ok {
		_spec.SetField(education.FieldDegreeType, field.TypeString, value)
		_node.DegreeType = value
	}
	if value, ok := _c.mutation.AreaOfStudy(); ok {
		_spec.SetField(education.FieldAreaOfStudy, field.TypeString, value)
		_node.AreaOfStudy = value
	}
	if value, ok := _c.mutation.CurrentlyStudying(); ok {
		_spec.SetField(education.FieldCurrentlyStudying, field.TypeBool, value)
		_node.CurrentlyStudying = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(education.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(education.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EducationCreateBulk is the builder for creating many Education entities in bulk.
type EducationCreateBulk struct {
	config
	err      error
	builders []*EducationCreate
}

// Save creates the Education entities in the database.
func (_c *EducationCreateBulk) Save(ctx context.Context) ([]*Education, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Education, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EducationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EducationCreateBulk) SaveX(ctx context.Context) []*Education {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EducationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EducationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
