// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/experience"
	"api/ent/predicate"
	"api/ent/user"
	"api/ent/userskillassociation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExperienceUpdate is the builder for updating Experience entities.
type ExperienceUpdate struct {
	config
	hooks    []Hook
	mutation *ExperienceMutation
}

// Where appends a list predicates to the ExperienceUpdate builder.
func (_u *ExperienceUpdate) Where(ps ...predicate.Experience) *ExperienceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *ExperienceUpdate) SetCompanyName(v string) *ExperienceUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableCompanyName(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ExperienceUpdate) SetStartDate(v time.Time) *ExperienceUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableStartDate(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ExperienceUpdate) SetEndDate(v time.Time) *ExperienceUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableEndDate(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ExperienceUpdate) ClearEndDate() *ExperienceUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetCurrentPlace sets the "current_place" field.
func (_u *ExperienceUpdate) SetCurrentPlace(v bool) *ExperienceUpdate {
	_u.mutation.SetCurrentPlace(v)
	return _u
}

// SetNillableCurrentPlace sets the "current_place" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableCurrentPlace(v *bool) *ExperienceUpdate {
	if v != nil {
		_u.SetCurrentPlace(*v)
	}
	return _u
}

// ClearCurrentPlace clears the value of the "current_place" field.
func (_u *ExperienceUpdate) ClearCurrentPlace() *ExperienceUpdate {
	_u.mutation.ClearCurrentPlace()
	return _u
}

// SetPosition sets the "position" field.
func (_u *ExperienceUpdate) SetPosition(v string) *ExperienceUpdate {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillablePosition(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExperienceUpdate) SetUserID(v uint) *ExperienceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableUserID(v *uint) *ExperienceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ExperienceUpdate) SetCreatedAt(v time.Time) *ExperienceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableCreatedAt(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ExperienceUpdate) ClearCreatedAt() *ExperienceUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceUpdate) SetUpdatedAt(v time.Time) *ExperienceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableUpdatedAt(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExperienceUpdate) ClearUpdatedAt() *ExperienceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExperienceUpdate) SetDescription(v string) *ExperienceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableDescription(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ExperienceUpdate) ClearDescription() *ExperienceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ExperienceUpdate) SetUser(v *User) *ExperienceUpdate {
	return _u.SetUserID(v.ID)
}

// AddUserSkillAssociationIDs adds the "user_skill_association" edge to the UserSkillAssociation entity by IDs.
func (_u *ExperienceUpdate) AddUserSkillAssociationIDs(ids ...uint) *ExperienceUpdate {
	_u.mutation.AddUserSkillAssociationIDs(ids...)
	return _u
}

// AddUserSkillAssociation adds the "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *ExperienceUpdate) AddUserSkillAssociation(v ...*UserSkillAssociation) *ExperienceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSkillAssociationIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_u *ExperienceUpdate) Mutation() *ExperienceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ExperienceUpdate) ClearUser() *ExperienceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearUserSkillAssociation clears all "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *ExperienceUpdate) ClearUserSkillAssociation() *ExperienceUpdate {
	_u.mutation.ClearUserSkillAssociation()
	return _u
}

// RemoveUserSkillAssociationIDs removes the "user_skill_association" edge to UserSkillAssociation entities by IDs.
func (_u *ExperienceUpdate) RemoveUserSkillAssociationIDs(ids ...uint) *ExperienceUpdate {
	_u.mutation.RemoveUserSkillAssociationIDs(ids...)
	return _u
}

// RemoveUserSkillAssociation removes "user_skill_association" edges to UserSkillAssociation entities.
func (_u *ExperienceUpdate) RemoveUserSkillAssociation(v ...*UserSkillAssociation) *ExperienceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSkillAssociationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExperienceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExperienceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Experience.user"`)
	}
	return nil
}

func (_u *ExperienceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experience.Table, experience.Columns, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(experience.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(experience.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(experience.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(experience.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPlace(); ok {
		_spec.SetField(experience.FieldCurrentPlace, field.TypeBool, value)
	}
	if _u.mutation.CurrentPlaceCleared() {
		_spec.ClearField(experience.FieldCurrentPlace, field.TypeBool)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(experience.FieldPosition, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(experience.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(experience.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(experience.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(experience.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(experience.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSkillAssociationIDs(); len(nodes) > 0 && !_u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExperienceUpdateOne is the builder for updating a single Experience entity.
type ExperienceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExperienceMutation
}

// SetCompanyName sets the "company_name" field.
func (_u *ExperienceUpdateOne) SetCompanyName(v string) *ExperienceUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableCompanyName(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ExperienceUpdateOne) SetStartDate(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableStartDate(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ExperienceUpdateOne) SetEndDate(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableEndDate(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ExperienceUpdateOne) ClearEndDate() *ExperienceUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetCurrentPlace sets the "current_place" field.
func (_u *ExperienceUpdateOne) SetCurrentPlace(v bool) *ExperienceUpdateOne {
	_u.mutation.SetCurrentPlace(v)
	return _u
}

// SetNillableCurrentPlace sets the "current_place" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableCurrentPlace(v *bool) *ExperienceUpdateOne {
	if v != nil {
		_u.SetCurrentPlace(*v)
	}
	return _u
}

// ClearCurrentPlace clears the value of the "current_place" field.
func (_u *ExperienceUpdateOne) ClearCurrentPlace() *ExperienceUpdateOne {
	_u.mutation.ClearCurrentPlace()
	return _u
}

// SetPosition sets the "position" field.
func (_u *ExperienceUpdateOne) SetPosition(v string) *ExperienceUpdateOne {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillablePosition(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExperienceUpdateOne) SetUserID(v uint) *ExperienceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableUserID(v *uint) *ExperienceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ExperienceUpdateOne) SetCreatedAt(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableCreatedAt(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ExperienceUpdateOne) ClearCreatedAt() *ExperienceUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceUpdateOne) SetUpdatedAt(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableUpdatedAt(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExperienceUpdateOne) ClearUpdatedAt() *ExperienceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExperienceUpdateOne) SetDescription(v string) *ExperienceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableDescription(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ExperienceUpdateOne) ClearDescription() *ExperienceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ExperienceUpdateOne) SetUser(v *User) *ExperienceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddUserSkillAssociationIDs adds the "user_skill_association" edge to the UserSkillAssociation entity by IDs.
func (_u *ExperienceUpdateOne) AddUserSkillAssociationIDs(ids ...uint) *ExperienceUpdateOne {
	_u.mutation.AddUserSkillAssociationIDs(ids...)
	return _u
}

// AddUserSkillAssociation adds the "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *ExperienceUpdateOne) AddUserSkillAssociation(v ...*UserSkillAssociation) *ExperienceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSkillAssociationIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_u *ExperienceUpdateOne) Mutation() *ExperienceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ExperienceUpdateOne) ClearUser() *ExperienceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearUserSkillAssociation clears all "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *ExperienceUpdateOne) ClearUserSkillAssociation() *ExperienceUpdateOne {
	_u.mutation.ClearUserSkillAssociation()
	return _u
}

// RemoveUserSkillAssociationIDs removes the "user_skill_association" edge to UserSkillAssociation entities by IDs.
func (_u *ExperienceUpdateOne) RemoveUserSkillAssociationIDs(ids ...uint) *ExperienceUpdateOne {
	_u.mutation.RemoveUserSkillAssociationIDs(ids...)
	return _u
}

// RemoveUserSkillAssociation removes "user_skill_association" edges to UserSkillAssociation entities.
func (_u *ExperienceUpdateOne) RemoveUserSkillAssociation(v ...*UserSkillAssociation) *ExperienceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSkillAssociationIDs(ids...)
}

// Where appends a list predicates to the ExperienceUpdate builder.
func (_u *ExperienceUpdateOne) Where(ps ...predicate.Experience) *ExperienceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExperienceUpdateOne) Select(field string, fields ...string) *ExperienceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Experience entity.
func (_u *ExperienceUpdateOne) Save(ctx context.Context) (*Experience, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceUpdateOne) SaveX(ctx context.Context) *Experience {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExperienceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Experience.user"`)
	}
	return nil
}

func (_u *ExperienceUpdateOne) sqlSave(ctx context.Context) (_node *Experience, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experience.Table, experience.Columns, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Experience.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, experience.FieldID)
		for _, f := range fields {
			if !experience.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != experience.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(experience.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(experience.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(experience.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(experience.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPlace(); ok {
		_spec.SetField(experience.FieldCurrentPlace, field.TypeBool, value)
	}
	if _u.mutation.CurrentPlaceCleared() {
		_spec.ClearField(experience.FieldCurrentPlace, field.TypeBool)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(experience.FieldPosition, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(experience.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(experience.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(experience.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(experience.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(experience.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSkillAssociationIDs(); len(nodes) > 0 && !_u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Experience{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
