// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/experience"
	"api/ent/user"
	"api/ent/userskillassociation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExperienceCreate is the builder for creating a Experience entity.
type ExperienceCreate struct {
	config
	mutation *ExperienceMutation
	hooks    []Hook
}

// SetCompanyName sets the "company_name" field.
func (_c *ExperienceCreate) SetCompanyName(v string) *ExperienceCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *ExperienceCreate) SetStartDate(v time.Time) *ExperienceCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *ExperienceCreate) SetEndDate(v time.Time) *ExperienceCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableEndDate(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetCurrentPlace sets the "current_place" field.
func (_c *ExperienceCreate) SetCurrentPlace(v bool) *ExperienceCreate {
	_c.mutation.SetCurrentPlace(v)
	return _c
}

// SetNillableCurrentPlace sets the "current_place" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableCurrentPlace(v *bool) *ExperienceCreate {
	if v != nil {
		_c.SetCurrentPlace(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *ExperienceCreate) SetPosition(v string) *ExperienceCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ExperienceCreate) SetUserID(v uint) *ExperienceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExperienceCreate) SetCreatedAt(v time.Time) *ExperienceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableCreatedAt(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExperienceCreate) SetUpdatedAt(v time.Time) *ExperienceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableUpdatedAt(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExperienceCreate) SetDescription(v string) *ExperienceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableDescription(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExperienceCreate) SetID(v uint) *ExperienceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ExperienceCreate) SetUser(v *User) *ExperienceCreate {
	return _c.SetUserID(v.ID)
}

// AddUserSkillAssociationIDs adds the "user_skill_association" edge to the UserSkillAssociation entity by IDs.
func (_c *ExperienceCreate) AddUserSkillAssociationIDs(ids ...uint) *ExperienceCreate {
	_c.mutation.AddUserSkillAssociationIDs(ids...)
	return _c
}

// AddUserSkillAssociation adds the "user_skill_association" edges to the UserSkillAssociation entity.
func (_c *ExperienceCreate) AddUserSkillAssociation(v ...*UserSkillAssociation) *ExperienceCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserSkillAssociationIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_c *ExperienceCreate) Mutation() *ExperienceMutation {
	return _c.mutation
}

// Save creates the Experience in the database.
func (_c *ExperienceCreate) Save(ctx context.Context) (*Experience, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExperienceCreate) SaveX(ctx context.Context) *Experience {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExperienceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := experience.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := experience.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExperienceCreate) check() error {
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "Experience.company_name"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Experience.start_date"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Experience.position"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Experience.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Experience.user"`)}
	}
	return nil
}

func (_c *ExperienceCreate) sqlSave(ctx context.Context) (*Experience, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExperienceCreate) createSpec() (*Experience, *sqlgraph.CreateSpec) {
	var (
		_node = &Experience{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(experience.Table, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(experience.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(experience.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(experience.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.CurrentPlace(); ok {
		_spec.SetField(experience.FieldCurrentPlace, field.TypeBool, value)
		_node.CurrentPlace = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(experience.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(experience.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(experience.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UserSkillAssociationTable,
			Columns: []string{experience.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExperienceCreateBulk is the builder for creating many Experience entities in bulk.
type ExperienceCreateBulk struct {
	config
	err      error
	builders []*ExperienceCreate
}

// Save creates the Experience entities in the database.
func (_c *ExperienceCreateBulk) Save(ctx context.Context) ([]*Experience, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Experience, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExperienceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExperienceCreateBulk) SaveX(ctx context.Context) []*Experience {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
