// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/education"
	"api/ent/experience"
	"api/ent/schema"
	"api/ent/skill"
	"api/ent/user"
	"api/ent/userskillassociation"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	educationFields := schema.Education{}.Fields()
	_ = educationFields
	// educationDescCreatedAt is the schema descriptor for created_at field.
	educationDescCreatedAt := educationFields[10].Descriptor()
	// education.DefaultCreatedAt holds the default value on creation for the created_at field.
	education.DefaultCreatedAt = educationDescCreatedAt.Default.(func() time.Time)
	// educationDescUpdatedAt is the schema descriptor for updated_at field.
	educationDescUpdatedAt := educationFields[11].Descriptor()
	// education.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	education.DefaultUpdatedAt = educationDescUpdatedAt.Default.(func() time.Time)
	// education.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	education.UpdateDefaultUpdatedAt = educationDescUpdatedAt.UpdateDefault.(func() time.Time)
	experienceFields := schema.Experience{}.Fields()
	_ = experienceFields
	// experienceDescCreatedAt is the schema descriptor for created_at field.
	experienceDescCreatedAt := experienceFields[7].Descriptor()
	// experience.DefaultCreatedAt holds the default value on creation for the created_at field.
	experience.DefaultCreatedAt = experienceDescCreatedAt.Default.(func() time.Time)
	// experienceDescUpdatedAt is the schema descriptor for updated_at field.
	experienceDescUpdatedAt := experienceFields[8].Descriptor()
	// experience.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	experience.DefaultUpdatedAt = experienceDescUpdatedAt.Default.(func() time.Time)
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillFields[2].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillFields[3].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	userskillassociationFields := schema.UserSkillAssociation{}.Fields()
	_ = userskillassociationFields
	// userskillassociationDescCreatedAt is the schema descriptor for created_at field.
	userskillassociationDescCreatedAt := userskillassociationFields[4].Descriptor()
	// userskillassociation.DefaultCreatedAt holds the default value on creation for the created_at field.
	userskillassociation.DefaultCreatedAt = userskillassociationDescCreatedAt.Default.(func() time.Time)
	// userskillassociationDescUpdatedAt is the schema descriptor for updated_at field.
	userskillassociationDescUpdatedAt := userskillassociationFields[5].Descriptor()
	// userskillassociation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userskillassociation.DefaultUpdatedAt = userskillassociationDescUpdatedAt.Default.(func() time.Time)
}
