// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/predicate"
	"api/ent/project"
	"api/ent/skill"
	"api/ent/techsctack"
	"api/ent/userskillassociation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks    []Hook
	mutation *SkillMutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *SkillUpdate) SetIcon(v string) *SkillUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableIcon(v *string) *SkillUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *SkillUpdate) ClearIcon() *SkillUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdate) SetCreatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCreatedAt(v *time.Time) *SkillUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SkillUpdate) ClearCreatedAt() *SkillUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdate) SetUpdatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableUpdatedAt(v *time.Time) *SkillUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkillUpdate) ClearUpdatedAt() *SkillUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddUserSkillAssociationIDs adds the "user_skill_association" edge to the UserSkillAssociation entity by IDs.
func (_u *SkillUpdate) AddUserSkillAssociationIDs(ids ...uint) *SkillUpdate {
	_u.mutation.AddUserSkillAssociationIDs(ids...)
	return _u
}

// AddUserSkillAssociation adds the "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *SkillUpdate) AddUserSkillAssociation(v ...*UserSkillAssociation) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSkillAssociationIDs(ids...)
}

// AddTechstackIDs adds the "techstack" edge to the TechSctack entity by IDs.
func (_u *SkillUpdate) AddTechstackIDs(ids ...uint) *SkillUpdate {
	_u.mutation.AddTechstackIDs(ids...)
	return _u
}

// AddTechstack adds the "techstack" edges to the TechSctack entity.
func (_u *SkillUpdate) AddTechstack(v ...*TechSctack) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechstackIDs(ids...)
}

// AddProjectIDs adds the "project" edge to the Project entity by IDs.
func (_u *SkillUpdate) AddProjectIDs(ids ...uint) *SkillUpdate {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProject adds the "project" edges to the Project entity.
func (_u *SkillUpdate) AddProject(v ...*Project) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUserSkillAssociation clears all "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *SkillUpdate) ClearUserSkillAssociation() *SkillUpdate {
	_u.mutation.ClearUserSkillAssociation()
	return _u
}

// RemoveUserSkillAssociationIDs removes the "user_skill_association" edge to UserSkillAssociation entities by IDs.
func (_u *SkillUpdate) RemoveUserSkillAssociationIDs(ids ...uint) *SkillUpdate {
	_u.mutation.RemoveUserSkillAssociationIDs(ids...)
	return _u
}

// RemoveUserSkillAssociation removes "user_skill_association" edges to UserSkillAssociation entities.
func (_u *SkillUpdate) RemoveUserSkillAssociation(v ...*UserSkillAssociation) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSkillAssociationIDs(ids...)
}

// ClearTechstack clears all "techstack" edges to the TechSctack entity.
func (_u *SkillUpdate) ClearTechstack() *SkillUpdate {
	_u.mutation.ClearTechstack()
	return _u
}

// RemoveTechstackIDs removes the "techstack" edge to TechSctack entities by IDs.
func (_u *SkillUpdate) RemoveTechstackIDs(ids ...uint) *SkillUpdate {
	_u.mutation.RemoveTechstackIDs(ids...)
	return _u
}

// RemoveTechstack removes "techstack" edges to TechSctack entities.
func (_u *SkillUpdate) RemoveTechstack(v ...*TechSctack) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechstackIDs(ids...)
}

// ClearProject clears all "project" edges to the Project entity.
func (_u *SkillUpdate) ClearProject() *SkillUpdate {
	_u.mutation.ClearProject()
	return _u
}

// RemoveProjectIDs removes the "project" edge to Project entities by IDs.
func (_u *SkillUpdate) RemoveProjectIDs(ids ...uint) *SkillUpdate {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProject removes "project" edges to Project entities.
func (_u *SkillUpdate) RemoveProject(v ...*Project) *SkillUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(skill.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(skill.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(skill.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skill.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSkillAssociationIDs(); len(nodes) > 0 && !_u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TechstackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechstackIDs(); len(nodes) > 0 && !_u.mutation.TechstackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechstackIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectIDs(); len(nodes) > 0 && !_u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillMutation
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *SkillUpdateOne) SetIcon(v string) *SkillUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableIcon(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *SkillUpdateOne) ClearIcon() *SkillUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdateOne) SetCreatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCreatedAt(v *time.Time) *SkillUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SkillUpdateOne) ClearCreatedAt() *SkillUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdateOne) SetUpdatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableUpdatedAt(v *time.Time) *SkillUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkillUpdateOne) ClearUpdatedAt() *SkillUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddUserSkillAssociationIDs adds the "user_skill_association" edge to the UserSkillAssociation entity by IDs.
func (_u *SkillUpdateOne) AddUserSkillAssociationIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.AddUserSkillAssociationIDs(ids...)
	return _u
}

// AddUserSkillAssociation adds the "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *SkillUpdateOne) AddUserSkillAssociation(v ...*UserSkillAssociation) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSkillAssociationIDs(ids...)
}

// AddTechstackIDs adds the "techstack" edge to the TechSctack entity by IDs.
func (_u *SkillUpdateOne) AddTechstackIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.AddTechstackIDs(ids...)
	return _u
}

// AddTechstack adds the "techstack" edges to the TechSctack entity.
func (_u *SkillUpdateOne) AddTechstack(v ...*TechSctack) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechstackIDs(ids...)
}

// AddProjectIDs adds the "project" edge to the Project entity by IDs.
func (_u *SkillUpdateOne) AddProjectIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProject adds the "project" edges to the Project entity.
func (_u *SkillUpdateOne) AddProject(v ...*Project) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUserSkillAssociation clears all "user_skill_association" edges to the UserSkillAssociation entity.
func (_u *SkillUpdateOne) ClearUserSkillAssociation() *SkillUpdateOne {
	_u.mutation.ClearUserSkillAssociation()
	return _u
}

// RemoveUserSkillAssociationIDs removes the "user_skill_association" edge to UserSkillAssociation entities by IDs.
func (_u *SkillUpdateOne) RemoveUserSkillAssociationIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.RemoveUserSkillAssociationIDs(ids...)
	return _u
}

// RemoveUserSkillAssociation removes "user_skill_association" edges to UserSkillAssociation entities.
func (_u *SkillUpdateOne) RemoveUserSkillAssociation(v ...*UserSkillAssociation) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSkillAssociationIDs(ids...)
}

// ClearTechstack clears all "techstack" edges to the TechSctack entity.
func (_u *SkillUpdateOne) ClearTechstack() *SkillUpdateOne {
	_u.mutation.ClearTechstack()
	return _u
}

// RemoveTechstackIDs removes the "techstack" edge to TechSctack entities by IDs.
func (_u *SkillUpdateOne) RemoveTechstackIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.RemoveTechstackIDs(ids...)
	return _u
}

// RemoveTechstack removes "techstack" edges to TechSctack entities.
func (_u *SkillUpdateOne) RemoveTechstack(v ...*TechSctack) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechstackIDs(ids...)
}

// ClearProject clears all "project" edges to the Project entity.
func (_u *SkillUpdateOne) ClearProject() *SkillUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// RemoveProjectIDs removes the "project" edge to Project entities by IDs.
func (_u *SkillUpdateOne) RemoveProjectIDs(ids ...uint) *SkillUpdateOne {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProject removes "project" edges to Project entities.
func (_u *SkillUpdateOne) RemoveProject(v ...*Project) *SkillUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(skill.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(skill.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(skill.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skill.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSkillAssociationIDs(); len(nodes) > 0 && !_u.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TechstackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechstackIDs(); len(nodes) > 0 && !_u.mutation.TechstackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechstackIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.TechstackTable,
			Columns: []string{skill.TechstackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectIDs(); len(nodes) > 0 && !_u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   skill.ProjectTable,
			Columns: skill.ProjectPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
