// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/predicate"
	"api/ent/skill"
	"api/ent/techsctack"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TechSctackUpdate is the builder for updating TechSctack entities.
type TechSctackUpdate struct {
	config
	hooks    []Hook
	mutation *TechSctackMutation
}

// Where appends a list predicates to the TechSctackUpdate builder.
func (_u *TechSctackUpdate) Where(ps ...predicate.TechSctack) *TechSctackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TechSctackUpdate) SetName(v string) *TechSctackUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TechSctackUpdate) SetNillableName(v *string) *TechSctackUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TechSctackUpdate) SetSkillID(v uint) *TechSctackUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TechSctackUpdate) SetNillableSkillID(v *uint) *TechSctackUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TechSctackUpdate) SetUserID(v uint) *TechSctackUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TechSctackUpdate) SetNillableUserID(v *uint) *TechSctackUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TechSctackUpdate) SetCreatedAt(v time.Time) *TechSctackUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TechSctackUpdate) SetNillableCreatedAt(v *time.Time) *TechSctackUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *TechSctackUpdate) ClearCreatedAt() *TechSctackUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TechSctackUpdate) SetUpdatedAt(v time.Time) *TechSctackUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TechSctackUpdate) SetNillableUpdatedAt(v *time.Time) *TechSctackUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TechSctackUpdate) ClearUpdatedAt() *TechSctackUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TechSctackUpdate) SetSkill(v *Skill) *TechSctackUpdate {
	return _u.SetSkillID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TechSctackUpdate) SetUser(v *User) *TechSctackUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TechSctackMutation object of the builder.
func (_u *TechSctackUpdate) Mutation() *TechSctackMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TechSctackUpdate) ClearSkill() *TechSctackUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TechSctackUpdate) ClearUser() *TechSctackUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TechSctackUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TechSctackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TechSctackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TechSctackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TechSctackUpdate) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TechSctack.skill"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TechSctack.user"`)
	}
	return nil
}

func (_u *TechSctackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(techsctack.Table, techsctack.Columns, sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(techsctack.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(techsctack.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(techsctack.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(techsctack.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(techsctack.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.SkillTable,
			Columns: []string{techsctack.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.SkillTable,
			Columns: []string{techsctack.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.UserTable,
			Columns: []string{techsctack.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.UserTable,
			Columns: []string{techsctack.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{techsctack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TechSctackUpdateOne is the builder for updating a single TechSctack entity.
type TechSctackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TechSctackMutation
}

// SetName sets the "name" field.
func (_u *TechSctackUpdateOne) SetName(v string) *TechSctackUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TechSctackUpdateOne) SetNillableName(v *string) *TechSctackUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TechSctackUpdateOne) SetSkillID(v uint) *TechSctackUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TechSctackUpdateOne) SetNillableSkillID(v *uint) *TechSctackUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TechSctackUpdateOne) SetUserID(v uint) *TechSctackUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TechSctackUpdateOne) SetNillableUserID(v *uint) *TechSctackUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TechSctackUpdateOne) SetCreatedAt(v time.Time) *TechSctackUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TechSctackUpdateOne) SetNillableCreatedAt(v *time.Time) *TechSctackUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *TechSctackUpdateOne) ClearCreatedAt() *TechSctackUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TechSctackUpdateOne) SetUpdatedAt(v time.Time) *TechSctackUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TechSctackUpdateOne) SetNillableUpdatedAt(v *time.Time) *TechSctackUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TechSctackUpdateOne) ClearUpdatedAt() *TechSctackUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TechSctackUpdateOne) SetSkill(v *Skill) *TechSctackUpdateOne {
	return _u.SetSkillID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TechSctackUpdateOne) SetUser(v *User) *TechSctackUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TechSctackMutation object of the builder.
func (_u *TechSctackUpdateOne) Mutation() *TechSctackMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TechSctackUpdateOne) ClearSkill() *TechSctackUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TechSctackUpdateOne) ClearUser() *TechSctackUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TechSctackUpdate builder.
func (_u *TechSctackUpdateOne) Where(ps ...predicate.TechSctack) *TechSctackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TechSctackUpdateOne) Select(field string, fields ...string) *TechSctackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TechSctack entity.
func (_u *TechSctackUpdateOne) Save(ctx context.Context) (*TechSctack, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TechSctackUpdateOne) SaveX(ctx context.Context) *TechSctack {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TechSctackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TechSctackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TechSctackUpdateOne) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TechSctack.skill"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TechSctack.user"`)
	}
	return nil
}

func (_u *TechSctackUpdateOne) sqlSave(ctx context.Context) (_node *TechSctack, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(techsctack.Table, techsctack.Columns, sqlgraph.NewFieldSpec(techsctack.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TechSctack.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, techsctack.FieldID)
		for _, f := range fields {
			if !techsctack.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != techsctack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(techsctack.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(techsctack.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(techsctack.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(techsctack.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(techsctack.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.SkillTable,
			Columns: []string{techsctack.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.SkillTable,
			Columns: []string{techsctack.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.UserTable,
			Columns: []string{techsctack.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   techsctack.UserTable,
			Columns: []string{techsctack.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TechSctack{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{techsctack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
