// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/predicate"
	"api/ent/userskillassociation"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSkillAssociationDelete is the builder for deleting a UserSkillAssociation entity.
type UserSkillAssociationDelete struct {
	config
	hooks    []Hook
	mutation *UserSkillAssociationMutation
}

// Where appends a list predicates to the UserSkillAssociationDelete builder.
func (_d *UserSkillAssociationDelete) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserSkillAssociationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSkillAssociationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserSkillAssociationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userskillassociation.Table, sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserSkillAssociationDeleteOne is the builder for deleting a single UserSkillAssociation entity.
type UserSkillAssociationDeleteOne struct {
	_d *UserSkillAssociationDelete
}

// Where appends a list predicates to the UserSkillAssociationDelete builder.
func (_d *UserSkillAssociationDeleteOne) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserSkillAssociationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userskillassociation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSkillAssociationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
