// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/experience"
	"api/ent/predicate"
	"api/ent/skill"
	"api/ent/userskillassociation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSkillAssociationUpdate is the builder for updating UserSkillAssociation entities.
type UserSkillAssociationUpdate struct {
	config
	hooks    []Hook
	mutation *UserSkillAssociationMutation
}

// Where appends a list predicates to the UserSkillAssociationUpdate builder.
func (_u *UserSkillAssociationUpdate) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExperienceID sets the "experience_id" field.
func (_u *UserSkillAssociationUpdate) SetExperienceID(v uint) *UserSkillAssociationUpdate {
	_u.mutation.SetExperienceID(v)
	return _u
}

// SetNillableExperienceID sets the "experience_id" field if the given value is not nil.
func (_u *UserSkillAssociationUpdate) SetNillableExperienceID(v *uint) *UserSkillAssociationUpdate {
	if v != nil {
		_u.SetExperienceID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *UserSkillAssociationUpdate) SetSkillID(v uint) *UserSkillAssociationUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *UserSkillAssociationUpdate) SetNillableSkillID(v *uint) *UserSkillAssociationUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *UserSkillAssociationUpdate) SetPercentage(v int32) *UserSkillAssociationUpdate {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *UserSkillAssociationUpdate) SetNillablePercentage(v *int32) *UserSkillAssociationUpdate {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *UserSkillAssociationUpdate) AddPercentage(v int32) *UserSkillAssociationUpdate {
	_u.mutation.AddPercentage(v)
	return _u
}

// ClearPercentage clears the value of the "percentage" field.
func (_u *UserSkillAssociationUpdate) ClearPercentage() *UserSkillAssociationUpdate {
	_u.mutation.ClearPercentage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserSkillAssociationUpdate) SetCreatedAt(v time.Time) *UserSkillAssociationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserSkillAssociationUpdate) SetNillableCreatedAt(v *time.Time) *UserSkillAssociationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *UserSkillAssociationUpdate) ClearCreatedAt() *UserSkillAssociationUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSkillAssociationUpdate) SetUpdatedAt(v time.Time) *UserSkillAssociationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserSkillAssociationUpdate) SetNillableUpdatedAt(v *time.Time) *UserSkillAssociationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserSkillAssociationUpdate) ClearUpdatedAt() *UserSkillAssociationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_u *UserSkillAssociationUpdate) SetExperience(v *Experience) *UserSkillAssociationUpdate {
	return _u.SetExperienceID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *UserSkillAssociationUpdate) SetSkill(v *Skill) *UserSkillAssociationUpdate {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the UserSkillAssociationMutation object of the builder.
func (_u *UserSkillAssociationUpdate) Mutation() *UserSkillAssociationMutation {
	return _u.mutation
}

// ClearExperience clears the "experience" edge to the Experience entity.
func (_u *UserSkillAssociationUpdate) ClearExperience() *UserSkillAssociationUpdate {
	_u.mutation.ClearExperience()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *UserSkillAssociationUpdate) ClearSkill() *UserSkillAssociationUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSkillAssociationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSkillAssociationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSkillAssociationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSkillAssociationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSkillAssociationUpdate) check() error {
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSkillAssociation.experience"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSkillAssociation.skill"`)
	}
	return nil
}

func (_u *UserSkillAssociationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userskillassociation.Table, userskillassociation.Columns, sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(userskillassociation.FieldPercentage, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(userskillassociation.FieldPercentage, field.TypeInt32, value)
	}
	if _u.mutation.PercentageCleared() {
		_spec.ClearField(userskillassociation.FieldPercentage, field.TypeInt32)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userskillassociation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(userskillassociation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userskillassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(userskillassociation.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.ExperienceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.ExperienceTable,
			Columns: []string{userskillassociation.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.ExperienceTable,
			Columns: []string{userskillassociation.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.SkillTable,
			Columns: []string{userskillassociation.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.SkillTable,
			Columns: []string{userskillassociation.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userskillassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSkillAssociationUpdateOne is the builder for updating a single UserSkillAssociation entity.
type UserSkillAssociationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSkillAssociationMutation
}

// SetExperienceID sets the "experience_id" field.
func (_u *UserSkillAssociationUpdateOne) SetExperienceID(v uint) *UserSkillAssociationUpdateOne {
	_u.mutation.SetExperienceID(v)
	return _u
}

// SetNillableExperienceID sets the "experience_id" field if the given value is not nil.
func (_u *UserSkillAssociationUpdateOne) SetNillableExperienceID(v *uint) *UserSkillAssociationUpdateOne {
	if v != nil {
		_u.SetExperienceID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *UserSkillAssociationUpdateOne) SetSkillID(v uint) *UserSkillAssociationUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *UserSkillAssociationUpdateOne) SetNillableSkillID(v *uint) *UserSkillAssociationUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *UserSkillAssociationUpdateOne) SetPercentage(v int32) *UserSkillAssociationUpdateOne {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *UserSkillAssociationUpdateOne) SetNillablePercentage(v *int32) *UserSkillAssociationUpdateOne {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *UserSkillAssociationUpdateOne) AddPercentage(v int32) *UserSkillAssociationUpdateOne {
	_u.mutation.AddPercentage(v)
	return _u
}

// ClearPercentage clears the value of the "percentage" field.
func (_u *UserSkillAssociationUpdateOne) ClearPercentage() *UserSkillAssociationUpdateOne {
	_u.mutation.ClearPercentage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserSkillAssociationUpdateOne) SetCreatedAt(v time.Time) *UserSkillAssociationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserSkillAssociationUpdateOne) SetNillableCreatedAt(v *time.Time) *UserSkillAssociationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *UserSkillAssociationUpdateOne) ClearCreatedAt() *UserSkillAssociationUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSkillAssociationUpdateOne) SetUpdatedAt(v time.Time) *UserSkillAssociationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserSkillAssociationUpdateOne) SetNillableUpdatedAt(v *time.Time) *UserSkillAssociationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserSkillAssociationUpdateOne) ClearUpdatedAt() *UserSkillAssociationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_u *UserSkillAssociationUpdateOne) SetExperience(v *Experience) *UserSkillAssociationUpdateOne {
	return _u.SetExperienceID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *UserSkillAssociationUpdateOne) SetSkill(v *Skill) *UserSkillAssociationUpdateOne {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the UserSkillAssociationMutation object of the builder.
func (_u *UserSkillAssociationUpdateOne) Mutation() *UserSkillAssociationMutation {
	return _u.mutation
}

// ClearExperience clears the "experience" edge to the Experience entity.
func (_u *UserSkillAssociationUpdateOne) ClearExperience() *UserSkillAssociationUpdateOne {
	_u.mutation.ClearExperience()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *UserSkillAssociationUpdateOne) ClearSkill() *UserSkillAssociationUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// Where appends a list predicates to the UserSkillAssociationUpdate builder.
func (_u *UserSkillAssociationUpdateOne) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSkillAssociationUpdateOne) Select(field string, fields ...string) *UserSkillAssociationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSkillAssociation entity.
func (_u *UserSkillAssociationUpdateOne) Save(ctx context.Context) (*UserSkillAssociation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSkillAssociationUpdateOne) SaveX(ctx context.Context) *UserSkillAssociation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSkillAssociationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSkillAssociationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSkillAssociationUpdateOne) check() error {
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSkillAssociation.experience"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSkillAssociation.skill"`)
	}
	return nil
}

func (_u *UserSkillAssociationUpdateOne) sqlSave(ctx context.Context) (_node *UserSkillAssociation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userskillassociation.Table, userskillassociation.Columns, sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSkillAssociation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userskillassociation.FieldID)
		for _, f := range fields {
			if !userskillassociation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userskillassociation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(userskillassociation.FieldPercentage, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(userskillassociation.FieldPercentage, field.TypeInt32, value)
	}
	if _u.mutation.PercentageCleared() {
		_spec.ClearField(userskillassociation.FieldPercentage, field.TypeInt32)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userskillassociation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(userskillassociation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userskillassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(userskillassociation.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.ExperienceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.ExperienceTable,
			Columns: []string{userskillassociation.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.ExperienceTable,
			Columns: []string{userskillassociation.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.SkillTable,
			Columns: []string{userskillassociation.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.SkillTable,
			Columns: []string{userskillassociation.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSkillAssociation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userskillassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
