// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/experience"
	"api/ent/skill"
	"api/ent/userskillassociation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSkillAssociationCreate is the builder for creating a UserSkillAssociation entity.
type UserSkillAssociationCreate struct {
	config
	mutation *UserSkillAssociationMutation
	hooks    []Hook
}

// SetExperienceID sets the "experience_id" field.
func (_c *UserSkillAssociationCreate) SetExperienceID(v uint) *UserSkillAssociationCreate {
	_c.mutation.SetExperienceID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *UserSkillAssociationCreate) SetSkillID(v uint) *UserSkillAssociationCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetPercentage sets the "percentage" field.
func (_c *UserSkillAssociationCreate) SetPercentage(v int32) *UserSkillAssociationCreate {
	_c.mutation.SetPercentage(v)
	return _c
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_c *UserSkillAssociationCreate) SetNillablePercentage(v *int32) *UserSkillAssociationCreate {
	if v != nil {
		_c.SetPercentage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSkillAssociationCreate) SetCreatedAt(v time.Time) *UserSkillAssociationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSkillAssociationCreate) SetNillableCreatedAt(v *time.Time) *UserSkillAssociationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSkillAssociationCreate) SetUpdatedAt(v time.Time) *UserSkillAssociationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSkillAssociationCreate) SetNillableUpdatedAt(v *time.Time) *UserSkillAssociationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserSkillAssociationCreate) SetID(v uint) *UserSkillAssociationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_c *UserSkillAssociationCreate) SetExperience(v *Experience) *UserSkillAssociationCreate {
	return _c.SetExperienceID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_c *UserSkillAssociationCreate) SetSkill(v *Skill) *UserSkillAssociationCreate {
	return _c.SetSkillID(v.ID)
}

// Mutation returns the UserSkillAssociationMutation object of the builder.
func (_c *UserSkillAssociationCreate) Mutation() *UserSkillAssociationMutation {
	return _c.mutation
}

// Save creates the UserSkillAssociation in the database.
func (_c *UserSkillAssociationCreate) Save(ctx context.Context) (*UserSkillAssociation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSkillAssociationCreate) SaveX(ctx context.Context) *UserSkillAssociation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSkillAssociationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSkillAssociationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSkillAssociationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userskillassociation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userskillassociation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSkillAssociationCreate) check() error {
	if _, ok := _c.mutation.ExperienceID(); !ok {
		return &ValidationError{Name: "experience_id", err: errors.New(`ent: missing required field "UserSkillAssociation.experience_id"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "UserSkillAssociation.skill_id"`)}
	}
	if len(_c.mutation.ExperienceIDs()) == 0 {
		return &ValidationError{Name: "experience", err: errors.New(`ent: missing required edge "UserSkillAssociation.experience"`)}
	}
	if len(_c.mutation.SkillIDs()) == 0 {
		return &ValidationError{Name: "skill", err: errors.New(`ent: missing required edge "UserSkillAssociation.skill"`)}
	}
	return nil
}

func (_c *UserSkillAssociationCreate) sqlSave(ctx context.Context) (*UserSkillAssociation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSkillAssociationCreate) createSpec() (*UserSkillAssociation, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSkillAssociation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userskillassociation.Table, sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Percentage(); ok {
		_spec.SetField(userskillassociation.FieldPercentage, field.TypeInt32, value)
		_node.Percentage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userskillassociation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userskillassociation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.ExperienceTable,
			Columns: []string{userskillassociation.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExperienceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userskillassociation.SkillTable,
			Columns: []string{userskillassociation.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkillID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserSkillAssociationCreateBulk is the builder for creating many UserSkillAssociation entities in bulk.
type UserSkillAssociationCreateBulk struct {
	config
	err      error
	builders []*UserSkillAssociationCreate
}

// Save creates the UserSkillAssociation entities in the database.
func (_c *UserSkillAssociationCreateBulk) Save(ctx context.Context) ([]*UserSkillAssociation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSkillAssociation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSkillAssociationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSkillAssociationCreateBulk) SaveX(ctx context.Context) []*UserSkillAssociation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSkillAssociationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSkillAssociationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
