// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// Dob holds the value of the "dob" field.
	Dob time.Time `json:"dob,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// GithubUsername holds the value of the "github_username" field.
	GithubUsername string `json:"github_username,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MobileNumber holds the value of the "mobile_number" field.
	MobileNumber int32 `json:"mobile_number,omitempty"`
	// AddressBlock holds the value of the "address_block" field.
	AddressBlock string `json:"address_block,omitempty"`
	// AddressStreet holds the value of the "address_street" field.
	AddressStreet string `json:"address_street,omitempty"`
	// RecidentialCountry holds the value of the "recidential_country" field.
	RecidentialCountry string `json:"recidential_country,omitempty"`
	// Nationality holds the value of the "nationality" field.
	Nationality string `json:"nationality,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Educations holds the value of the educations edge.
	Educations []*Education `json:"educations,omitempty"`
	// Experiences holds the value of the experiences edge.
	Experiences []*Experience `json:"experiences,omitempty"`
	// Documents holds the value of the documents edge.
	Documents []*Document `json:"documents,omitempty"`
	// Techstack holds the value of the techstack edge.
	Techstack []*TechSctack `json:"techstack,omitempty"`
	// Project holds the value of the project edge.
	Project []*Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// EducationsOrErr returns the Educations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) EducationsOrErr() ([]*Education, error) {
	if e.loadedTypes[0] {
		return e.Educations, nil
	}
	return nil, &NotLoadedError{edge: "educations"}
}

// ExperiencesOrErr returns the Experiences value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ExperiencesOrErr() ([]*Experience, error) {
	if e.loadedTypes[1] {
		return e.Experiences, nil
	}
	return nil, &NotLoadedError{edge: "experiences"}
}

// DocumentsOrErr returns the Documents value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DocumentsOrErr() ([]*Document, error) {
	if e.loadedTypes[2] {
		return e.Documents, nil
	}
	return nil, &NotLoadedError{edge: "documents"}
}

// TechstackOrErr returns the Techstack value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TechstackOrErr() ([]*TechSctack, error) {
	if e.loadedTypes[3] {
		return e.Techstack, nil
	}
	return nil, &NotLoadedError{edge: "techstack"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectOrErr() ([]*Project, error) {
	if e.loadedTypes[4] {
		return e.Project, nil
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID, user.FieldMobileNumber:
			values[i] = new(sql.NullInt64)
		case user.FieldFirstName, user.FieldLastName, user.FieldUsername, user.FieldPassword, user.FieldEmail, user.FieldGithubUsername, user.FieldDescription, user.FieldAddressBlock, user.FieldAddressStreet, user.FieldRecidentialCountry, user.FieldNationality:
			values[i] = new(sql.NullString)
		case user.FieldDob, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case user.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				_m.FirstName = value.String
			}
		case user.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				_m.LastName = value.String
			}
		case user.FieldDob:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dob", values[i])
			} else if value.Valid {
				_m.Dob = value.Time
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldGithubUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field github_username", values[i])
			} else if value.Valid {
				_m.GithubUsername = value.String
			}
		case user.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldMobileNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mobile_number", values[i])
			} else if value.Valid {
				_m.MobileNumber = int32(value.Int64)
			}
		case user.FieldAddressBlock:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_block", values[i])
			} else if value.Valid {
				_m.AddressBlock = value.String
			}
		case user.FieldAddressStreet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_street", values[i])
			} else if value.Valid {
				_m.AddressStreet = value.String
			}
		case user.FieldRecidentialCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recidential_country", values[i])
			} else if value.Valid {
				_m.RecidentialCountry = value.String
			}
		case user.FieldNationality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nationality", values[i])
			} else if value.Valid {
				_m.Nationality = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEducations queries the "educations" edge of the User entity.
func (_m *User) QueryEducations() *EducationQuery {
	return NewUserClient(_m.config).QueryEducations(_m)
}

// QueryExperiences queries the "experiences" edge of the User entity.
func (_m *User) QueryExperiences() *ExperienceQuery {
	return NewUserClient(_m.config).QueryExperiences(_m)
}

// QueryDocuments queries the "documents" edge of the User entity.
func (_m *User) QueryDocuments() *DocumentQuery {
	return NewUserClient(_m.config).QueryDocuments(_m)
}

// QueryTechstack queries the "techstack" edge of the User entity.
func (_m *User) QueryTechstack() *TechSctackQuery {
	return NewUserClient(_m.config).QueryTechstack(_m)
}

// QueryProject queries the "project" edge of the User entity.
func (_m *User) QueryProject() *ProjectQuery {
	return NewUserClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("first_name=")
	builder.WriteString(_m.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(_m.LastName)
	builder.WriteString(", ")
	builder.WriteString("dob=")
	builder.WriteString(_m.Dob.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("github_username=")
	builder.WriteString(_m.GithubUsername)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("mobile_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.MobileNumber))
	builder.WriteString(", ")
	builder.WriteString("address_block=")
	builder.WriteString(_m.AddressBlock)
	builder.WriteString(", ")
	builder.WriteString("address_street=")
	builder.WriteString(_m.AddressStreet)
	builder.WriteString(", ")
	builder.WriteString("recidential_country=")
	builder.WriteString(_m.RecidentialCountry)
	builder.WriteString(", ")
	builder.WriteString("nationality=")
	builder.WriteString(_m.Nationality)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
