// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Education is the predicate function for education builders.
type Education func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSkillAssociation is the predicate function for userskillassociation builders.
type UserSkillAssociation func(*sql.Selector)
