// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Education is the predicate function for education builders.
type Education func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// TechSctack is the predicate function for techsctack builders.
type TechSctack func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSkillAssociation is the predicate function for userskillassociation builders.
type UserSkillAssociation func(*sql.Selector)
